### ISSUE TITLE
软件兼容性

### ISSUE THREAD

**Issue by mushroom-x** [Singein/Pycman#2]
考虑到部分OS(例如Ubuntu)默认的Python版本号是2的问题

**Comment by Singein** [comment]
添加对python2.7的支持

**Comment by Singein** [comment]
![图片](https://user-images.githubusercontent.com/18239246/69791794-34998e00-1200-11ea-953b-bad586245536.png)
@mushroom-x 简单的解决了下， 不过这都是假定用户电脑上安装了python3.5 +

**Comment by Singein** [comment]
@mushroom-x 其实这里的主要逻辑在于：linux或者mac用户电脑上的 python 指令到底是对应到 python2.x还是python3.x    这属于类unix上特有的python2 3共存问题，但是对于Windows来说，目前也只是假定用户的python指向的就是3.5+

**Comment by Singein** [comment]
windows用户自己改环境变量去吧

**Comment by Singein** [comment]
目前这不是一个很理想的解决方案。 暂时先这样， 重点放在功能和稳定性上。
